### ISSUE TITLE
RedSync Not Working - Disappear from Board Menu

### ISSUE THREAD

**Issue by chandora** [pvisionjp/redsync#22]
**Describe the bug**
RedSync has disappeared from the Board menu.

**To Reproduce**
1. Open the Trello board with RedSync installed
2. Click the Board menu

**Expected behavior**
Some menus for RedSync are displayed.

**Screenshots**
None

**Environment (please complete the following information):**
None

**Additional context**
None

**Comment by pvisionjp** [comment]
Another powerup has been experiencing the same issue, and its developer has found its cause.

https://community.developer.atlassian.com/t/csp-unsafe-eval-since-last-evening/66818

At this writing, no answer from the Trello team, but it is an unexpected change of behavior on the Trello server.

I have made a change in the CSP header to accept 'unsafe-eval' as a temtative solution.

**Comment by pvisionjp** [comment]
The Trello team has acknowledged this issue:

https://trello.status.atlassian.com/incidents/rss78hbhbf2c

In summary, it is a bug in the Trello service.
