### ISSUE TITLE
Not working options for task status

### ISSUE THREAD

**Issue by Balk128** [pvisionjp/redsync#66]
Hello!
Please, help me. Why this options are not working?
![Screenshot_1633](https://github.com/pvisionjp/redsync/assets/175032340/f6c4ed80-edeb-4702-8827-f83d003a744c)
![Screenshot_1634](https://github.com/pvisionjp/redsync/assets/175032340/af900ef3-27af-4508-818c-047e1378bb42)
![Screenshot_1635](https://github.com/pvisionjp/redsync/assets/175032340/cd517689-c72d-4449-a6dc-fc6fed8dd567)
![Screenshot_1636](https://github.com/pvisionjp/redsync/assets/175032340/c13b021c-f85c-4402-83c4-ec69fec0c5a1)
![Screenshot_1637](https://github.com/pvisionjp/redsync/assets/175032340/12a9fdba-d778-428c-9ba2-eb3372657229)

Redmine version                4.2.0.stable

**Comment by pvisionjp** [comment]
Hello, thank you for using RedSync.

Please check the following settings.

Settings > Redmine Server (left-most tab in the Settings panel) > Server

I infer you have checked the "Access using JSONP" option.
If so, "Synchronize from Card to Issue" is disabled since JSONP does not allow the Redmine server to be updated.

You don't need to use the JSONP option if your Redmine server supports CORS.

Please check the following sections of the User's Guide for details.
https://pvision.jp/apps/2022/03/17/redsync-power-up/#user-guide-en-administrators-guide
https://pvision.jp/apps/2022/03/17/redsync-power-up/#user-guide-en-settings

Please let me know if the above inference does not meet your situation or if you need further assistance.

Best regards,

**Comment by pvisionjp** [comment]
Oops, I overlooked the other options you asked for.

The "Editable on Card" and "Custom Fileds—Trello to Redmine" options are currently blocked due to JSONP (if my assumption in the previous post is current). In addition, they are available only with the Pro Plan or Personal Plan.

https://pvision.jp/apps/2022/06/15/redsync-free-version-vs-pro-version/

Best regards,

**Comment by Balk128** [comment]
Hello, thank you!
But if i disable JSONP, I have a new mistake:

**Comment by pvisionjp** [comment]
Hello,

“Access using JSONP” is an option of RedSync settings.
You can find the option on the following pannel:

![image](https://github.com/pvisionjp/redsync/assets/102245978/95ebe1d3-a303-4af2-9156-720f3d800ee3)

I understand you are on the Pro plan and want to update some fields from Card to Issue.
Due to its specifications, JSONP does not allow the updating of Redmine, so it is not an option that meets your needs.

Does your Redmine support CORS?
CORS is a specification for the HTTP protocol that allows Redmine to be updated.
If yes, you don’t need to enable the JSONP interface in either RedSync or Redmine. (You still need to enable the REST interface in Redmine.)

If not, is your Redmine server accessible from the internet?
If yes, please try to enable the “Accessing via Proxy” option on the RedSync settings panel.
This option has a disadvantage in terms of performance; it works without CORS support.

Unfortunately, if both CORS and internet access are not supported, there is no way to update the fields from Card to Issue.

As a last resort, if you have the privilege of modifying the Redmine installation, you can enable CORS yourself or ask your administrator to do it. There are a couple of ways, and I explained one of them in the following article:
https://pvision.jp/apps/2022/07/02/step-by-step-install-redmine-5-0-with-ruby-3-1-on-ubuntu/

I hope the above clarifies the options and we can find a solution.

Best regards,

**Comment by Balk128** [comment]
Hello, thank you so much!
It works with Access via Proxy!!!
![Screenshot_1643](https://github.com/pvisionjp/redsync/assets/175032340/aadef506-0d82-4e3c-b376-a110c7302c82)
![Screenshot_1644](https://github.com/pvisionjp/redsync/assets/175032340/8fda8db9-9a4b-4159-a9f0-465010e9907f)
